"""§5.2 offline-fallback bundle: predictions.jsonl + reports/ as a zip.

The organizer's §5.2 fallback path expects (per `赛题4` README):
  - `predictions.jsonl`: one line per task, each line the same
    `AnalyzeResponse` JSON shape served by `/v1/analyze` (so the grader
    can replay the same evidence checks it'd run on the live URL).
  - `reports/{id}.html`: one rendered HTML report per task id, matching
    `report_html_url` in the corresponding prediction line.

This module assembles the two together into a single in-memory zip
that the `/v1/batch` route streams back when the input manifest is in
the official dialect (manifest rows carry `user_query` / `type` /
`parent_id`). The xlsx renderer (`render_xlsx`) is the alternative
output for the native dialect; both consume the same `BatchResult`
list, just shaped differently.

Why a zip rather than a multipart response: the grader's offline
ingestion is documented as "predictions.jsonl + a reports/ directory"
— a single zip lets the operator unzip into the expected layout
without per-file routing. The `reports/` prefix is preserved inside
the archive so unzipping at the right cwd lands the files where the
grader expects.
"""

from __future__ import annotations

import io
import json
import zipfile
from datetime import UTC, datetime

from app.batch.runner import BatchResult


def render_official_bundle(
    results: list[BatchResult], *, archive_name: str = "predictions"
) -> bytes:
    """Serialize batch results to a zip containing predictions.jsonl + reports/.

    `archive_name` is the top-level directory name inside the zip — when
    the operator unzips with `unzip predictions.zip`, they get a
    `predictions/` directory containing the artifacts. The grader's
    documentation pins the file names but is flexible about the wrapper
    directory.

    Tasks that errored out (network failure, planner-rejected plan,
    etc.) still get a line in `predictions.jsonl` so the grader sees the
    full task set — the line carries `is_refusal=true` with an error
    narrative in `summary` rather than fabricating findings.

    `skipped` tasks (today: any `type=follow_up` row, see runner.py) are
    written with `summary` documenting the skip and `is_refusal=false`,
    so the grader's "is this a refusal?" check doesn't double-count
    skipped follow-ups as refused.

    File layout uses the manifest `task.id` as the key everywhere:
    `predictions.jsonl` rows carry `id == task.id`, `report_html_url`
    points at `reports/{task.id}.html`, and the HTML files in the
    archive are named `{task.id}.html`. The internal eval-only id
    (`response.id`, e.g. `eval_analysis_<hex>`) is dropped from the
    bundle entirely — it would only confuse the grader, who expects
    one consistent id per task. (CodeRabbit fix on PR #21.)
    """

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        # Manifest of what's in the archive — useful for the operator to
        # eyeball without unzipping. Generated by us; not part of the
        # graded artifacts.
        zf.writestr(
            f"{archive_name}/MANIFEST.txt",
            _manifest_text(results),
        )
        # predictions.jsonl: one task per line. We keep the order from
        # the input manifest so the grader can re-key by id without
        # worrying about reordering.
        predictions_lines: list[str] = []
        for result in results:
            payload = _result_to_prediction(result)
            predictions_lines.append(
                json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
            )
        zf.writestr(
            f"{archive_name}/predictions.jsonl",
            "\n".join(predictions_lines) + "\n",
        )
        # reports/: one per ok / error result that produced HTML. Skipped
        # tasks contribute no file because there's nothing to render.
        # Filename is `{task.id}.html` so it lines up with the
        # `report_html_url` we wrote into predictions.jsonl above; the
        # internal `response.id` is irrelevant to the grader.
        for result in results:
            if result.status != "ok" or result.response is None:
                continue
            html = _extract_report_html(result)
            if html is None:
                continue
            zf.writestr(
                f"{archive_name}/reports/{result.task.id}.html",
                html,
            )
    return buf.getvalue()


def _manifest_text(results: list[BatchResult]) -> str:
    """Plain-text summary at the top of the zip — operator-facing."""

    by_status: dict[str, int] = {}
    for r in results:
        by_status[r.status] = by_status.get(r.status, 0) + 1
    lines = [
        "TableTalker offline-batch bundle",
        f"Generated: {datetime.now(UTC).isoformat(timespec='seconds')}",
        f"Tasks total: {len(results)}",
    ]
    for status, count in sorted(by_status.items()):
        lines.append(f"  - {status}: {count}")
    lines.extend(
        [
            "",
            "Layout:",
            "  predictions.jsonl    one line per task (赛题4 §5.2 contract)",
            "  reports/{id}.html    one HTML per task that produced a report",
            "  MANIFEST.txt         this file (informational)",
            "",
            "predictions.jsonl per-line shape == AnalyzeResponse from",
            "/v1/analyze; see docs/submission-contract.md.",
        ]
    )
    return "\n".join(lines) + "\n"


def _result_to_prediction(result: BatchResult) -> dict:
    """One BatchResult → one predictions.jsonl line.

    On success: emit the AnalyzeResponse verbatim.
    On error: emit a refusal-shaped record carrying the error narrative
              so the grader's id-keyed lookup still finds the task.
    On skip:  emit a non-refusal record explaining the skip; charts /
              findings empty.
    """

    task_id = result.task.id
    if result.status == "ok" and result.response is not None:
        # Pass through the AnalyzeResponse but rewrite both `id` and
        # `report_html_url` so the bundle is internally consistent: the
        # grader keys by task.id, and the HTML in reports/ is also
        # named after task.id (see render_official_bundle below). The
        # internal eval id (response.id) is dropped because it has no
        # meaning to the grader.
        body = result.response.model_dump(mode="json")
        body["id"] = task_id
        body["report_html_url"] = f"reports/{task_id}.html"
        return body

    # Failure / skip share the same shape — empty findings/charts/recs,
    # narrative carries the diagnostic. is_refusal=true for hard errors
    # (the system declined to answer); false for skips (we didn't try).
    is_refusal = result.status == "error"
    summary = result.error or "task did not produce a response"
    return {
        "id": task_id,
        "report_html_url": "",
        "summary": summary,
        "findings": [],
        "charts": [],
        "recommendations": [],
        "is_refusal": is_refusal,
        "confidence": 0.0,
    }


def _extract_report_html(result: BatchResult) -> str | None:
    """Pull the rendered HTML from REPORT_STORE for `result.response.id`.

    Local import avoids module-load circularity (REPORT_STORE pulls in
    Jinja templates, which we don't need to load just to parse a
    manifest). Returns None when the report isn't in the store —
    shouldn't happen for ok results but keeps the bundler defensive.
    """

    from app.report import REPORT_STORE

    response = result.response
    if response is None:
        return None
    return REPORT_STORE.get(response.id)  # str | None — None if evicted
